# Generated by Django 3.0 on 2019-12-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bnotes_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
